version: "3"
services:
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - redis-data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"

volumes:
  redis-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ~/DockerVolumes/redis/redis/data
networks:
  default:
    external:
      name: network-dev
